### PR TITLE
connect login/signup with backend

### PR DESCRIPTION
**Pull request by viviennecruz**
- added code for the login/signup to connect to the backend 
- fixed 1004 domain error (could not connect to the server), meaning the iPhone simulator could not connect to the server
    -  solution is to use 127.0.0.1 or your ip server instead of local host
- receiving invalid response error now but at least able to connect to the server

### CODE REVIEW

**Review by vivianneyee — COMMENTED** [review]
lgtm. merge main into this branch then I will approve

**Comment by viviennecruz** [comment]
> lgtm. merge main into this branch then I will approve

sounds good, im just gonna add an option for the user type for sign up then will merge main into this branch

**Comment by vivianneyee** [comment]
You may have to pull main again after my PR is merged because the login function returns a user object now. Maybe this can be passed to the home page so the users classes can be displayed, not sure how it works though.

**Comment by viviennecruz** [comment]
> You may have to pull main again after my PR is merged because the login function returns a user object now. Maybe this can be passed to the home page so the users classes can be displayed, not sure how it works though.

okay nice, yeah ill try adding that at once your pr is merged

**Comment by viviennecruz** [comment]
fixed an issue with passing the user id after logging in but it works now (succesfully retrieves the user's info). I changed the getUserID function to also return the role and schedule. I'm gonna finish the rest of the api connections in diff branches, I think the login/signup is ready to merge with main.

**Review by vivianneyee — APPROVED** [review]

**Pull request merged**
